#!/bin/bash

# Copy to .git/hooks in the project root
# E.g. cp pre-commit ../.git/hooks/ && chmod +x ../.git/hooks/pre-commit
CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

echo "Running ktlint..."
./gradlew ktlintFormat

RESULT=$?
if [ $RESULT -ne 0 ]; then
 echo "Ktlint error"
 exit 1
fi

echo "$CHANGED_FILES" | while read -r file; do
  if [ -f $file ]; then
    git add $file
  fi
done

exit 0
